version: '3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movies
    volumes:
      - ./db/movies:/docker-entrypoint-initdb.d/movies
      - mariadb_data:/var/lib/mysql
    networks:
      - pathe_network

  pathe_movies:
    build:
      context: ./pathe_movies
    depends_on:
      - mariadb
    ports:
      - 3005:3005
    networks:
      - pathe_network


  discord_tool:
    build:
      context: ./discord-tool
    depends_on:
      - pathe_movies
    ports:
      - 3002:3002
    networks:
      - pathe_network

  front:
    build:
      context: ./front/pathe
    ports:
      - 3000:3000
    depends_on:
      - pathe_movies
    networks:
      - pathe_network

volumes:
  mariadb_data:

networks:
  pathe_network: